syntax on

set t_8f=\[[38;2;%lu;%lu;%lum
set t_8b=\[[48;2;%lu;%lu;%lum
 
set runtimepath^=~/.vim/bundle/julia-vim
colorscheme slate
set number
set hlsearch
set tags=tags
" let g:indentLine_color_term = 100 " requires plugin
" let g:indentLine_char = ‘*’ " requires plugin

set conceallevel=1
" let g:indentLine_conceallevel=1 " requires plugin

set tabstop=4
set tabpagemax=1000
colorscheme slate

" The commands below are causing exiting issues on the Caltech cluster
"let g:netrw_banner = 0
"let g:netrw_liststyle = 3
"let g:netrw_browse_split = 4
"let g:netrw_altv = 1
"let g:netrw_winsize = 25
"augroup ProjectDrawer
"  autocmd!
"  autocmd VimEnter * :Vexplore
"augroup END
